# Generated by Django 5.0.3 on 2024-04-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0003_post_created_at_post_modified_at_post_view_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('post', models.ManyToManyField(related_name='hashtags', to='posts.post')),
            ],
        ),
    ]
