# Generated by Django 5.0.3 on 2024-05-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hashtags', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='post',
            field=models.ManyToManyField(related_name='hashtags', to='posts.post'),
        ),
    ]
