# Generated by Django 5.0.3 on 2024-04-29 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0002_initial'),
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Hashtag',
        ),
    ]
