# Generated by Django 5.0.3 on 2024-04-11 01:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 4, 11, 1, 25, 0, 661842, tzinfo=datetime.timezone.utc))),
                ('modified_at', models.DateTimeField(default=datetime.datetime(2024, 4, 11, 1, 25, 0, 661842, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
